### ISSUE TITLE
Design display of scroll depth data

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#177]
Data is reported in buckets like 10%, 20%... etc. The number can go beyond 100%, indicating a user has scrolled past a story and into the other material, including comments.

**Comment by livlab** [comment]
How does the counting past story work? also 0 (after story reaches 100%) to a 100% (end of page)?

**Comment by hampelm** [comment]
110, 120, 130% etc off to infinity. 
We can decide to ignore after some point, or visually condense

**Comment by livlab** [comment]
![pasted image at 2016_03_24 09_43 am](https://cloud.githubusercontent.com/assets/1936365/14028965/c63cfecc-f1d5-11e5-9f06-084783834b69.png)

for reference - the approach that people have responded to most positively so far. the screenshot gives context to the buckets, which people had otherwise a hard time distinguishing between scroll x time spent.

comments will be addressed separately.

**Comment by hampelm** [comment]
@livlab Is the bar width total # of visitors or % of visitors? I think it makes more sense as % (eg with one of the bars as 100% of engaged people) as that shows the dropoff. 

Here's one by % where people dropped off fast -- looks like maybe 1/3 of people made it to the end:  

![slack-imgs-1 com](https://cloud.githubusercontent.com/assets/86435/14087647/0b102d28-f4f9-11e5-8209-5744c21eb839.png) 

And one where most people kept reading:

![slack-imgs com](https://cloud.githubusercontent.com/assets/86435/14087661/1c2d7fca-f4f9-11e5-9a03-90f2bddda307.png)

Might be helpful to have a couple "% of visitors" tick marks at the bottom.

**Comment by brianboyer** [comment]
donezo
