### ISSUE TITLE
Explore alternatives to Google Chart

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#191]
- [ ] Explore alternatives
- [ ] make a decision on whether or not switching over makes sense

**Comment by hampelm** [comment]
My goal is to find something that:
- Allows for significant design flexibility, so we can implement the look we want
- Is robust enough to not require drawing from scratch, so we don't waste time reinventing charting and avoid introducing new bugs
- Ideally is available on-demand via an image API, so we don't need to upload, serve, and otherwise manage files. (Avoiding a S3 dependency)

So far, Google Image charts API provides quite a lot of design flexibility in a complete hosted API. The downside is we don't have total control over chart design and some aspects of the formatting are obscured by the confusing syntax, or simply not possible (eg custom fonts).

My default outcome is to stick with the current Google API. That would minimize tech work on charting for the prototype phase. My assumption is that the time would be better focused on new tracking and reporting. I'm searching to see if there is an obvious easier replacement that doesn't add significant dev burden. 

@livlab I wanted to put my current focus out there explicitly. Did I miss anything? Let me know if you'd like to refocus those priorities and assumptions -- totally open to it!

**Comment by hampelm** [comment]
ChartURL offers 200 free chart images/ mo, otherwise pricing from $14 (5,000 images): https://charturl.com/. Based on C3, so there's lots of control. 

Plot.ly ($20/mo): https://plot.ly/products/cloud/

**Comment by livlab** [comment]
In agreement!

**Comment by hampelm** [comment]
We ended up using matplotlib
