### ISSUE TITLE
Set up servers

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#33]
Stage
Production

**Comment by hampelm** [comment]
We have a production server. It's harder to do staging right now because of the limit on Slack integrations. If we can get another Slack app spot we can have a `BroadwayCarebot` -- carebot on stage! :dancers:. 

My feeling is we should wait until NPR has more integrations via a paid plan instead of booting an existing app.

**Comment by livlab** [comment]
lol

ok.

**Comment by livlab** [comment]
We have an extra integration slot if you feel like doing it on Phase Two though, just FYI.

**Comment by livlab** [comment]
Per https://github.com/thecarebot/carebot/wiki/Phase-Two scope, we'll do this next.
