### ISSUE TITLE
Decide how to schedule periodic calls to GA

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#42]

**Comment by hampelm** [comment]
It looks like Carebot 1 [checked for data every 30 minutes](https://github.com/nprapps/carebot/blob/fc9b87869137144c11ef021e9889b3d55c837ae3/crontab). 

I think we should refresh a little more often -- maybe every 15 minutes. 

The workflow would look something like this:
Every 15 minutes: 
- Poll the stories doc
- For each story, if the story isn't already in carebot's database, add the story title, URL and slug with a timestamp. (stop once we hit a story we already have; don't go through the whole list) 
- Record metrics for each story as a JSON blob. Can store as plain text for now (maybe use RDS / JSON datatypes later)
- If the story is greater than 4, 8, etc hours old, have Carebot mention the latest average viewing time. 
  *\* Don't report out if we have already reported for that timeframe. 
  *\* Note in the database (boolean fields?) that we have done the 4, 8, etc. hour reportouts. 

Alternately, instead of polling the stories doc, people could say:

```
@carebot, please track my-slug-here
```
